name: image_captioning
channels:
  - pytorch
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - cpuonly=2.0=0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py310hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=py310h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=3.0=0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.38.0=py310hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py310he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - python=3.10.19=hf701271_0
  - pytorch=2.5.1=gpu_mps_py310hbd1d365_204
  - pytorch-mutex=1.0=cpu
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - sympy=1.14.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=mps_py310h620d032_102
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.23.0=py310hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - nltk==3.9.2
      - packaging==25.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - regex==2025.11.3
      - six==1.17.0
      - tqdm==4.67.1
prefix: /Users/romyisrael/anaconda3/envs/image_captioning
